#https://medium.com/@yegorj/building-flutter-apks-and-ipas-on-travis-98d84d8e9b4
matrix:
  branches:
    only:
      - master
  env:
        - APK_NAME="Wellness_android.apk"
        - IPA_NAME="Wellness_ios.app"

  include:
    - os: linux
      language: android
      sudo: false
      jdk: oraclejdk8
      env:
      - APK_NAME="Wellness_android.apk"
      licenses:
        - android-sdk-preview-license-.+
        - android-sdk-license-.+
        - google-gdk-license-.+
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28 # match your targetVersion
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - fonts-droid
      install:
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1
        - export PATH=./flutter/bin:$PATH
        - flutter doctor
      script:
        - flutter packages get
        - flutter analyze --no-pub --no-current-package lib/ test/
        - flutter test --no-pub test/
        - flutter build apk --release
        - mv build/app/outputs/apk/release/app-release.apk $APK_NAME
        - echo "Apk name" "$APK_NAME"
#========================================================================================
    - os: osx
      language: generic
      osx_image: xcode10.2
      env:
      - IPA_NAME="Wellness_ios.app"
      addons:
        homebrew:
          update: true
          packages: python3
      install:
        - pip install six
        - brew update
        - brew install --HEAD usbmuxd
        - brew install --HEAD libimobiledevice
        - brew install ideviceinstaller
        - brew install ios-deploy
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1
        - export PATH=./flutter/bin:$PATH
        - flutter doctor
      script:
        - flutter packages get
        - flutter analyze --no-pub --no-current-package lib/ test/
        - flutter test --no-pub test/
        - flutter build ios --no-codesign
        #- flutter build ios --release
        - mv build/app/outputs/ios/iphoneos/Runner.app $IPA_NAME
        - echo "IPA name" "$IPA_NAME"

  deploy:
    provider: releases
    on:
      branch: master
    api_key:
      secure: "f6fe6be867e736938833f970aeeb6f86dc88ff66"
    file: 
      - $APK_NAME
      - $IPA_NAME
    overwrite: true
    skip_cleanup: true

  cache:
    directories:
      - $HOME/.pub-cache