#https://medium.com/@yegorj/building-flutter-apks-and-ipas-on-travis-98d84d8e9b4
matrix:
  include:
    - os: linux
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - fonts-droid
      matrix:
        allow_failures:
          - env: FLUTTER_VERSION=beta
      before_script:
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1
        - ./flutter/bin/flutter doctor
      script:
        - ./flutter/bin/flutter build apk
      cache:
        directories:
          - $HOME/shared/.pub-cache

branches:
  only: [master]
    - os: osx
      language: generic
      osx_image: xcode10.2
      addons:
        homebrew:
          update: true
          packages: python3
      before_script:
        - pip install six
        - brew update
        - brew install --HEAD usbmuxd
        - brew install --HEAD libimobiledevice
        - brew install ideviceinstaller
        - brew install ios-deploy
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1
        - flutter doctor -v
      script:
        - ./flutter/bin/flutter -v build ios --no-codesign

      cache:
        directories:
          - $HOME/.pub-cache