--- 
language: generic
os: osx
osx_image: xcode10.2

before_install: 
  - "chmod +x travis/*"
before_script: 
  - travis/setup_android.sh
install: 
  - "git clone https://github.com/flutter/flutter.git -b stable --depth 1"
  - "export PATH=./flutter/bin:$PATH"
  - "flutter doctor"