#https://medium.com/@yegorj/building-flutter-apks-and-ipas-on-travis-98d84d8e9b4
matrix:
  include:
    - os: linux
      language: android
      sudo: false
      jdk: oraclejdk8
      licenses:
        - android-sdk-preview-license-.+
        - android-sdk-license-.+
        - google-gdk-license-.+
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28 # match your targetVersion
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - fonts-droid
      install:
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1
        - export PATH=./flutter/bin:$PATH
        - flutter doctor
      script:
        - flutter packages get
        - flutter analyze --no-pub --no-current-package lib/ test/
        - flutter test --no-pub test/
        - flutter -v build apk
      env:
        - BUILD_TIME=$(date +'%Y%m%d%H%M%S') APK_NAME="${TRAVIS_TAG}_${BUILD_TIME}_Wellness.apk"
      
      before_deploy:
        - mv build/app/outputs/apk/release/app-release.apk $APK_NAME
      
      deploy:
        provider: releases
        api_key:
          secure: $github_deploy_api_key
        file: $APK_NAME
        skip_cleanup: true
        overwrite: true
        on:
          repo: marcojoao / SportingWellness
          branch: master
          condition: $TRAVIS_TAG =~ /^release-v\d+\.\d+\.\d+/ # when tag match release-vx.x.x, then push a relase and upload apk.


    - os: osx
      language: generic
      osx_image: xcode10.2
      addons:
        homebrew:
          update: true
          packages: python3
      install:
        - pip install six
        - brew update
        - brew install --HEAD usbmuxd
        - brew install --HEAD libimobiledevice
        - brew install ideviceinstaller
        - brew install ios-deploy
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1
        - export PATH=./flutter/bin:$PATH
        - flutter doctor
      script:
        - flutter packages get
        - flutter analyze --no-pub --no-current-package lib/ test/
        - flutter test --no-pub test/
        - flutter -v build ios --no-codesign
  cache:
    directories:
      - $HOME/.pub-cache