#https://medium.com/@yegorj/building-flutter-apks-and-ipas-on-travis-98d84d8e9b4
matrix:
  include:
    - os: linux
      language: node_js
      jdk: oraclejdk8
      sudo: required
      node_js:
        - "12"
      env:
        global:
          - ANDROID_SDK_ROOT=/opt/android
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - lib32stdc++6 
            - libstdc++6
            - curl
      before_script:
        - wget https://services.gradle.org/distributions/gradle-4.10.3-bin.zip
        - unzip -qq gradle-4.10.3-bin.zip
        - export GRADLE_HOME=`pwd`/gradle-4.10.3
        - export PATH=$GRADLE_HOME/bin:$PATH
        - mkdir -p /home/travis/.android
        - echo 'count=0' > /home/travis/.android/repositories.cfg
        - wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        - mkdir android-sdk-tools
        - unzip -qq sdk-tools-linux-4333796.zip -d android-sdk-tools
        - export PATH=`pwd`/android-sdk-tools/tools/bin:$PATH
        - mkdir -p $ANDROID_SDK_ROOT
        - yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "tools" "build-tools;28.0.3" "extras;android;m2repository" > /dev/null
        - export PATH=${ANDROID_SDK_ROOT}/tools/bin:$PATH
        - sdkmanager --list
        - git clone https://github.com/flutter/flutter.git -b beta --depth 1
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
      script:
        - flutter doctor -v
        - ./flutter/bin/flutter build apk
        
    - os: osx
      language: generic
      osx_image: xcode10.2
      addons:
        homebrew:
          update: true
          packages: python3
      before_script:
        - pip install six
        - brew update
        - brew install --HEAD usbmuxd
        - brew install --HEAD libimobiledevice
        - brew install ideviceinstaller
        - brew install ios-deploy
        - git clone https://github.com/flutter/flutter.git -b beta --depth 1
      script:
        - flutter doctor -v
        - ./flutter/bin/flutter -v build ios --no-codesign

cache:
  directories:
    - $HOME/.pub-cache
    - node_modules