#https://medium.com/@yegorj/building-flutter-apks-and-ipas-on-travis-98d84d8e9b4
matrix:
  include:
    - os: linux
      language: android

      licenses:
        - android-sdk-preview-license-.+
        - android-sdk-license-.+
        - google-gdk-license-.+

      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28 # match your targetVersion

      jdk: oraclejdk8

      sudo: false

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - fonts-droid
      cache:
        directories:
          - "$HOME/.pub-cache"
      install:
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1
        - export PATH=./flutter/bin:$PATH
        - flutter doctor

      script:
        - flutter build apk

    - os: osx
      language: generic
      osx_image: xcode10.2
      addons:
        homebrew:
          update: true
          packages: python3
      before_script:
        - pip install six
        - brew update
        - brew install --HEAD usbmuxd
        - brew install --HEAD libimobiledevice
        - brew install ideviceinstaller
        - brew install ios-deploy
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1
        - flutter doctor -v
      script:
        - ./flutter/bin/flutter -v build ios --no-codesign

      cache:
        directories:
          - $HOME/.pub-cache