name: Wellness
description: Sporting Wellness App.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  date_util: ^0.1.4
  intl: ^0.15.8
  syncfusion_flutter_charts: ^1.0.0-beta.3
  date_utils: ^0.1.0+2
  sembast: ^2.0.1
  path_provider: ^1.2.0
  equatable: ^0.4.0
  flutter_bloc: ^0.20.1
  enum_to_string: ^1.0.7
  image_picker: ^0.6.1+3
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.14.0
  flutter_offline: ^0.2.4+1
  root_checker: ^0.1.3
  flutter_form_builder: ^3.3.4
  carousel_slider: ^1.3.0
  material_design_icons_flutter: ^3.2.4096

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.5
  flutter_launcher_icons: "^0.7.2"
 
flutter_icons: 
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icons/ic_launcher.png"

flutter:
  assets: 
    - assets/
    - lang/
  uses-material-design: true