name: sporting_performance
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.5.2+2
  path:
  
  sembast: ^2.0.0+1
  path_provider: ^1.1.2
  equatable: ^0.3.0
  flutter_bloc: ^0.19.1
  enum_to_string: ^1.0.7

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.2"
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.1



flutter_icons: 
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/ic_launcher.png"

flutter:
  assets: 
    - assets/
  uses-material-design: true

fonts:
    - family: Spectral
      fonts:
        - asset: assets/fonts/Spectral-Regular.ttf
          weight: 400
        - asset: assets/fonts/Spectral-Medium.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
