name: Wellness
description: Sporting Wellness App.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  date_util: ^0.1.4
  intl: ^0.15.8
  syncfusion_flutter_charts: ^1.0.0-beta.3
  fluttertoast: ^3.1.0
  liquid_pull_to_refresh: ^1.1.1
  flutter_staggered_grid_view: ^0.3.0
  bezier_chart: ^1.0.12
  date_utils: ^0.1.0+2
  flutter_form_builder: ^3.3.1
  sembast: ^2.0.1
  path_provider: ^1.2.0
  equatable: ^0.3.0
  flutter_bloc: ^0.20.0
  enum_to_string: ^1.0.7
  font_awesome_flutter: ^8.5.0
  image_picker: ^0.6.0+17
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.5
  flutter_launcher_icons: "^0.7.2"


 
flutter_icons: 
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icons/ic_launcher.png"

flutter:
  assets: 
    - assets/
  uses-material-design: true

fonts:
    - family: Spectral
      fonts:
        - asset: assets/fonts/Spectral-Regular.ttf
          weight: 400
        - asset: assets/fonts/Spectral-Medium.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700